### ISSUE TITLE
Issue with Firefox after the update (added file upload)

### ISSUE THREAD

**Issue by zaykho** [kootstra-rene/enge-js#10]
Impossible to load a bios or a game anymore in Firefox (it does work on Chrome though), getting that error from the console log:

![dddss](https://user-images.githubusercontent.com/6943022/110535637-d22c7e80-8120-11eb-954d-5d38ee51faba.png)

` const fileList = evt.dataTransfer?.files || evt.target.files;`

I will investigate.

EDIT: this was tested with the [latest version](https://kootstra-rene.github.io/enge-js/)

**Comment by kootstra-rene** [comment]
already fixed please check

**Comment by kootstra-rene** [comment]
Duplicate of #9
