### ISSUE TITLE
Issue with L1, L2, R2 (inverted) and joystick axes

### ISSUE THREAD

**Issue by zaykho** [kootstra-rene/enge-js#11]
In _psx-core/gamepad.js_, L1, L2 and R2 _pad.buttons_ are inverted:

```
      if (pad.buttons[6].pressed) { device.hi &= ~0x04 } // l1
      if (pad.buttons[7].pressed) { device.hi &= ~0x01 } // l2
      if (pad.buttons[5].pressed) { device.hi &= ~0x08 } // r1
      if (pad.buttons[4].pressed) { device.hi &= ~0x02 } // r2
```

Should be 

```
      if (pad.buttons[4].pressed) { device.hi &= ~0x04 } // l1
      if (pad.buttons[6].pressed) { device.hi &= ~0x01 } // l2
      if (pad.buttons[5].pressed) { device.hi &= ~0x08 } // r1
      if (pad.buttons[7].pressed) { device.hi &= ~0x02 } // r2
```

Then, the joystick doesn't work properly because of the setting ( 1 / -1 ) which require the joystick to reach maximum range to pass the condition, which in a lot of situations won't happen due to the sticks getting older (dead zone and max range changing over time).

Instead in my tools, I usually use an average number like 0.4 to activate the stick range early (to counter the maximum range) but still with a higher number than 0.1 to create a dead zone (if not, the joystick will constantly move).

```
      if (pad.axes[0] === -1) { device.lo &= ~0x80 } // left
      if (pad.axes[0] ===  1) { device.lo &= ~0x20 } // right
      if (pad.axes[1] === -1) { device.lo &= ~0x10 } // up
      if (pad.axes[1] ===  1) { device.lo &= ~0x40 } // down
```

Should be 

```
      if (pad.axes[0] <= -0.4) { device.lo &= ~0x80 } // left
      if (pad.axes[0] >=  0.4) { device.lo &= ~0x20 } // right
      if (pad.axes[1] <= -0.4) { device.lo &= ~0x10 } // up
      if (pad.axes[1] >=  0.4) { device.lo &= ~0x40 } // down
```

The changes can be [seen here](https://github.com/kootstra-rene/enge-js/compare/main...zaykho:main), and [live test here](https://zaykho.github.io/enge-js/)

Tested on Vagrant Story, Wipeout 3 and Front Mission Alternative !

Also, here a [good site](https://gamepad-tester.com/) to compare/test the result

**Comment by kootstra-rene** [comment]
Thanks, I'll test this with [ps1-tests](https://github.com/JaCzekanski/ps1-tests)
