### ISSUE TITLE
Texture/effect glitch appear after the "fixed fillRectangle and added Q8 quality level " update

### ISSUE THREAD

**Issue by zaykho** [kootstra-rene/enge-js#13]
Front Mission Alternative display some glitch texture/effect after this update 774275640c6e00f17e00f288c95033d874243cb5

Before:
![GIF_b](https://user-images.githubusercontent.com/6943022/110973649-cc6fac80-835d-11eb-9831-a8a4197fa9bf.gif)

After:
![GIF_a](https://user-images.githubusercontent.com/6943022/110974123-764f3900-835e-11eb-83d1-61471a21e7a9.gif)

**Comment by kootstra-rene** [comment]
The issue should be fixed now. Could you verify?

**Comment by zaykho** [comment]
Yeah, issue fixed ! Nice !

**Comment by kootstra-rene** [comment]
Confirmed issue fix
