### ISSUE TITLE
Save States Architecture

### ISSUE THREAD

**Issue by nbarkhina** [kootstra-rene/enge-js#14]
I would like to try and implement a save state feature, what do you think would be required to do that? I noticed you said memory card is not implemented so I'm thinking save state might be easier. I am interested your opinion do I need to just capture the state of all the JavaScript objects? cpu, memory, etc.. ? what list of objects do you think is necessary? and just exclude the cdr image? does this sound like the correct approach

Thanks

**Comment by kootstra-rene** [comment]
Indeed pretty much the complete hardware state of the emulator, cdr image should not be necessary but at least it should verify if the correct disc is in. Another issue might be the video ram. I think it might be enough to save the 2048x512 texture but dunno for sure. Another issue is that you do not have binary data in localStorage so you need to have the binary data base64 encoded. You should really think on how the user wants it to work:
1) do I want do download the save state, so an user action
2) do I want the state save when I move away to another tab, and restore it when I get back to the tab?
Really curious on how you will implement this feature.

**Comment by nbarkhina** [comment]
Thanks for the information. I was thinking to probably save it in IndexedDB as a serialized object because that can store more data than localStorage. That can store binary as UInt8Array. Will have to see how many megabytes it would take. Then it can maybe display to the user the list of save states using the rom name as a key.

**Comment by kootstra-rene** [comment]
Having multiple save states is indeed a nice feature, if your fed-up with one game you can progress on another. Really enthusiastic now :-)

**Comment by zaykho** [comment]
An import/export (upload/download) would also be a good idea, to allow keeping the save state even after a full browser cleaning.

**Comment by nbarkhina** [comment]
@kootstra-rene would the cache object also need to be saved or would that get built at runtime?

const cache = new Map();

**Comment by kootstra-rene** [comment]
You can leave it out. Code that is not available will be recompiled.



Op za 13 mrt. 2021 21:25 schreef Neil Barkhina ***@***.***>:

**Comment by nbarkhina** [comment]
@kootstra-rene you can take a look at my pull request, I got it kind of working but I am probably missing some state that needs to be saved. Maybe you can take a look? the textures are also messed up on load but then seem to go back to normal if the screen changes.

**Comment by kootstra-rene** [comment]
I am currently testing your pull-request and found some points to think of
1) savestate for demos, the simplest test i could think of is running a demo and pause, saving the state, refresh browser load state and run. The demo should continue running. This scenario does not work but was also not discussed. However my guess that this is the easiest to start with as you do not need a CD image. The DB key could be a hash over the file being loaded.
2) This game i've tested did not seem to work so I have to look at the code in a little more detail. Give me some time

**Comment by nbarkhina** [comment]
Sounds good yeah I agree if the code ever changes and property names change then the old save states will no longer work. It's a difficult problem to solve but would be very cool. I tried to keep it simple with just a single save state per game so as not to add a lot of buttons and drop downs. It would be nice to be able to see what save states you have, maybe with a pop up modal.

**Comment by zaykho** [comment]
>     2. This game i've tested did not seem to work so I have to look at the code in a little more detail. Give me some time

Same thing here, tested with Vagrant Story. I tried to load the save state at various time (bios load, intro load, title screen etc...) and the result is always a black screen + UI of the game, nothing more.

**Comment by kootstra-rene** [comment]
I just finished implementing MemCard support (got a lucky break there) and now I am uncertain on whether this feature should be still on the list. I'd like to keep things as simple as possible and the code clean. This feature has a rather big impact on the code base and is difficult to maintain. I would like to close it if you agree.

**Comment by nbarkhina** [comment]
Sure no problem. If you ever decide to revisit this feature then hopefully this code will help you in some way.

**Comment by kootstra-rene** [comment]
Closing issue. Thanks for the effort and code. Never used indexedDB before so learned again something new.
