### ISSUE TITLE
Lego Racers (1999) - Graphical bugs

### ISSUE THREAD

**Issue by Chris2918** [kootstra-rene/enge-js#19]
There are graphical bugs in Lego Racers (1999).

![Screenshot 2021-11-22 2 18 55 PM](https://user-images.githubusercontent.com/37005770/143627102-edcc1b24-09fd-4857-b838-b0388ddc16fb.png)

![Screenshot 2021-11-23 2 50 13 PM](https://user-images.githubusercontent.com/37005770/143627103-618a71a4-bb35-4808-aa7c-223270352e84.png)

![Screenshot 2021-11-22 2 43 37 PM](https://user-images.githubusercontent.com/37005770/143627129-80d18994-fc36-4da5-8ff3-7211f69244cf.png)

The AI racers are just a glitched texture., except for one racer who is in a cutscene when you play on this track.
The ones with missing right leg, and missing polygons were fixed somehow. I am going to test this on another machine to see if this bug occurs as well.

**Comment by kootstra-rene** [comment]
More games have glitches.. I will have a look at it. Thanks for the bug report.

**Comment by kootstra-rene** [comment]
I made an initial fix. During the circuit race the AI race have some missing polygons but most issues seem to fixed now.

**Comment by kootstra-rene** [comment]
should also test with other games :-( a lot broke

**Comment by kootstra-rene** [comment]
I fixed the issue with minimal side effects. Can you verify that it is working properly now?

**Comment by Chris2918** [comment]
![Screenshot (306)](https://user-images.githubusercontent.com/37005770/143688297-365bd55e-ed6f-4a2d-a0d4-d8e043ab4ce7.png)

It looks like it is working. Thanks!

**Comment by kootstra-rene** [comment]
If you press the q1 button a few times until q4 and then refresh the page. You can enjoy it in a better resolution.

**Comment by kootstra-rene** [comment]
Thanks for confirming the fix
