### ISSUE TITLE
Load games on mobile

### ISSUE THREAD

**Issue by paulodeleo** [kootstra-rene/enge-js#2]
Wow, just loaded Tekken 3 using the latest link and it plays perfectly!

Makes me curious as how well could it run on my phone... but as the way to load games is by drag n drop, I assume there is no way to do it on mobile right now.

Maybe a feature like touch on top half of the canvas to load (upload prompt?) BIOS, bottom half to load game?

**Comment by paulodeleo** [comment]
Made a [quick hack](https://github.com/kootstra-rene/enge-js/compare/main...paulodeleo:main) to test it and it worked, just not at full speed on my mid range 2 year old Xiaomi Mi A2. But still impressive!

**Comment by kootstra-rene** [comment]
merged your changes to archive and adjusted the file upload button, thank you for the help
