### ISSUE TITLE
SCPH1001 shell graphics are broken

### ISSUE THREAD

**Issue by wheremyfoodat** [kootstra-rene/enge-js#30]
As you can see in the picture attached below, the colours for the splashes are wrong and the small balls are missing.
![image](https://user-images.githubusercontent.com/44909372/165083254-1b91c52e-51b6-4e25-a3c6-794ce28d5acb.png)

If it helps any, both the textures used for the splashes and the balls require VRAM readbacks. IIRC the BIOS will draw the ball texture and some colourful quads outside the display area, transfer them to main RAM with a VRAM readback, edit them on the CPU, then upload them to VRAM again to sample them in the shell. Fixing VRAM readbacks is what made the balls & splashes render properly for me when I was emulating the GPU.

CPU drawing colourful quads outside the display area to edit & sample them
![image](https://user-images.githubusercontent.com/44909372/165084020-7f136dc4-9f41-41e0-956e-58031c293f64.png)

The ball texture being drawn offline
![image](https://user-images.githubusercontent.com/44909372/165084207-a29ffd3f-bd8c-48cc-9827-e89435eb2b74.png)

The textures that get uploaded after reading back and processing the above
![image](https://user-images.githubusercontent.com/44909372/165084337-008a8201-c837-48db-a8cb-44f6cc93f621.png)

**Comment by kootstra-rene** [comment]
Thanks for the detailed explanation. At one point I decided not to do the readPixels due to performance issues but maybe I should re-evaluate that decision.

**Comment by kootstra-rene** [comment]
![image](https://user-images.githubusercontent.com/26738893/165321581-748360de-145d-487c-b4f6-cce9ca12df9c.png)

**Comment by kootstra-rene** [comment]
I just have to add the readPixels but adjust it accordingly to the Quality setting
