### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by Bobgills** [kootstra-rene/enge-js#36]
When I put in a bin file for the game I want to put in the logo stops flashing but then the page just freezes

**Comment by kootstra-rene** [comment]
Do not drag on the logo but on the screen area. But make sure that the bios is loaded first. Also by dragging on the screen area. The bios only needs te be loaded once.
When in doubt press the upload button in the top right corner and load the files.

The emulator supports bin and iso

**Comment by kootstra-rene** [comment]
closing this issue, as it works as expected (safe the games that do not yet work....)
