### ISSUE TITLE
Add gamepad support 

### ISSUE THREAD

**Issue by kootstra-rene** [kootstra-rene/enge-js#4]
Add gamepad support for better usability/experience

**Comment by zaykho** [comment]
I'm working on it right now.

I'm making a setting overlay (pressing "escape" to toggle it) where we can set up the controls (pad and keyboard), the audio volume, the window size, loading by input the necessary file (bios and game) and finally, a FPS counter.

**Comment by kootstra-rene** [comment]
wow, one thing at the time. first just the controls, all the other things are different stories/issues which you can create if you want to. But this story is just gamepad support. Lets not start with feature creep on day one :-)

**Comment by zaykho** [comment]
he, he, he.  :p

Ok, going for gamepad first.

**Comment by zaykho** [comment]
Made a first version [here](https://github.com/zaykho/enge-js/blob/main/docs/index.js)

I'm not used with github so sorry if it's not properly made.

**Comment by kootstra-rene** [comment]
Thanks, I have taken the code and put it in gamepad.js and credited you. I did not create a pull request from you repo because it contained more changes then just the gamepad feature. It works like a charm with my gamepad.
