### ISSUE TITLE
Ff7 replicable crash:

### ISSUE THREAD

**Issue by mogaku9** [kootstra-rene/enge-js#43]
When fighting the robot that appears after you meet Mr shinra for the first time, if you use Tifa's limit break, the entire emulator will crash.

**Comment by kootstra-rene** [comment]
Could you provide a savegame close to that point? Or the memory card image? The latter can be done by pasting the card1 or card2 local storage text string from the browser dev tools.

**Comment by ff7man** [comment]
[tifalimit_memorycard.txt](https://github.com/kootstra-rene/enge-js/files/13462870/tifalimit_memorycard.txt)
<img width="711" alt="Screenshot 2023-11-24 at 7 42 15 PM" src="https://github.com/kootstra-rene/enge-js/assets/116538902/4f030c30-a090-4bfc-8e7e-53c887cce7e0">
Here's what the crash looks like

**Comment by kootstra-rene** [comment]
thanks, i'll see what i can do

**Comment by kootstra-rene** [comment]
@ff7man your memcard image helped a lot and I was able to reproduce the problem. It seems to be related to Tekken 3 hanging so I think I know how to fix it.
