### ISSUE TITLE
Ridge Racer Type 4: Intro FMV quite glitchy

### ISSUE THREAD

**Issue by GithubPrankster** [kootstra-rene/enge-js#5]
Graphics flicker quite a bit between the correct imagery and what seems to be an area of _VRAM_ with text assets sneaking into view alongside the last column of the video being weirdly repeated to fill the others.

**Output from eNGE:**
![image](https://user-images.githubusercontent.com/33995085/110313386-1d417700-7fe5-11eb-8d06-5433be912560.png)
**Output from DuckStation**
![image](https://user-images.githubusercontent.com/33995085/110313686-8b863980-7fe5-11eb-99d8-fcf88402e912.png)

There might be an issue with blitting from the MDEC to VRAM but I'm not sure. Amazing work already though :D

**Comment by kootstra-rene** [comment]
The latest commit fixed MDEC timing it was only a factor 6 off *doh*. I have verified it and the intro now works. The rest of the game not yet... only time attack until the replay
