### ISSUE TITLE
Stuck in loading screen

### ISSUE THREAD

**Issue by zaykho** [kootstra-rene/enge-js#7]
So, this is an issue that was happening a lot when I first tested this emulator, getting stuck in loading screens.

Out of 5 tries, at least 1 or 2 times, the game would pass the first or second loading screen without problem and reach in-game. 

But since this morning, impossible to pass any loading screen before in-game, no matter the browser (chrome and FF) or the cache cleaned or not.

And the console log doesn't warn about anything, the page isn't frozen and it seems to just end up loading indefinitely (without crashing, freezing or pausing)

**The games tested are:**
1. Vagrant Story - PAL
2. Gran Turismo 2 - NTSC - arcade disc

With 2 different Bios: **SCPH-1001** & **SCPH-1002** and 2 different method (Bin+Cue and ISO).

GT2 doesn't pass the first loading screen and Vagrant Story doesn't pass the second loading screen, just before reaching in-game.

[Still, yesterday, it was possible to reach ingame after a lot of tries.](https://imgur.com/a/uAhg0YO)

**Comment by kootstra-rene** [comment]
Do you do a shift-F5 between different loads? because the emulator does not properly initialise on each file drop.

**Comment by zaykho** [comment]
Well, If I do Shift-F5 or even Ctrl-F5, the result is the same. (I precise that, there is still data in the localstorage).

If I do a complete cleanup (including localstorage and everything else), the issue still persist.

I even tested the emulator for the first time on Edge some minutes ago, same problem, stuck on loading screen.

I also re-extracted and checked the files (in other emu) and they work great, so I don't know what's going on.

**Comment by kootstra-rene** [comment]
With you code changes? what does the console window say because everything is working fine on my machine. Oh my god the dreaded work-on-my-machine :-)

**Comment by zaykho** [comment]
The console say nothing actually (I mean, nothing different than what is shown in those pictures I shared (when it was working).

Also, this is the exact same code that I got working yesterday, I didn't updated or modified yet.

I also tried the version of paulodeleo and the recent one merged one, and still the same issue.

**Comment by kootstra-rene** [comment]
what does chrome://gpu say because if the gpu is software it is slow as hell, otherwise i am kind a lost on what the issue could be

**Comment by zaykho** [comment]
[Here](https://i.imgur.com/pAqiJTG.png)

Though, it worked some times ago, so I wonder why it doesn't now. I do have a GTX 1080, and when it worked it was at full speed. (in fact, even when it's stuck on loading, it's still at full speed)

**Comment by kootstra-rene** [comment]
Gran Turismo 2 does not work properly, that i know it hangs at the initial screen. Timing is indeed an issue with that game. Vagrant Story I personally cannot check.

**Comment by zaykho** [comment]
Ok, I will test more games.

I may have chosen the worst games to test first. ;)

**Comment by zaykho** [comment]
The issue can be closed.

It was a bad dump I think, I redumped and this time it work properly (never stuck in loading anymore), still weird that ePSXe didn't show any issues.

**Comment by kootstra-rene** [comment]
as requested closing the issue
